### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by vdavez** [18F/samwise#3]
Samwise > Samwell

![](https://c2.staticflickr.com/8/7141/6807740433_06cef8eb58.jpg) ![](http://ia.media-imdb.com/images/M/MV5BMTQyODYyOTczMF5BMl5BanBnXkFtZTcwNjY0ODg4OQ@@._V1_SX640_SY720_.jpg)

**Comment by adelevie** [comment]
PRS ARE WELCOME.

**Comment by vdavez** [comment]
Closed per #4
